
2023-06-08 10:15:40,577	INFO worker.py:1625 -- Started a local Ray instance.
[36m(RolloutWorker pid=71720)[39m !RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:15:51,889	WARNING env.py:155 -- Your env doesn't have a .spec.max_episode_steps attribute. Your horizon will default to infinity, and your environment will not be reset.
[36m(RolloutWorker pid=71720)[39m starting game.
[36m(RolloutWorker pid=71720)[39m !RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=71720)[39m starting game.!RESETTING ENVIRONMENT!
[36m(RolloutWorker pid=71720)
[36m(RolloutWorker pid=71720)[39m starting game.
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:03.955 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:03.955 | INFO     | sc2.controller:create_game:37 - Creating new game
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:03.955 | INFO     | sc2.controller:create_game:38 - Map:     TrainingMapResource
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:03.956 | INFO     | sc2.controller:create_game:39 - Players: Bot ArmyBot(Terran), Computer Hard(Zerg, RandomBuild)
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:03.957 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:04.144 | ERROR    | sc2.protocol:__request:50 - Cannot receive: Connection already closed.
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:04.144 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at 59993...
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:04.145 | INFO     | sc2.sc2process:kill_all:33 - kill_switch: Process cleanup for 3 processes
[36m(RolloutWorker pid=71720)[39m Exception in thread Thread-2:
[36m(RolloutWorker pid=71720)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\protocol.py", line 45, in __request
[36m(RolloutWorker pid=71720)[39m     response_bytes = await self._ws.receive_bytes()
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_ws.py", line 281, in receive_bytes
[36m(RolloutWorker pid=71720)[39m     raise TypeError(f"Received message {msg.type}:{msg.data!r} is not bytes")
[36m(RolloutWorker pid=71720)[39m TypeError: Received message 257:None is not bytes
[36m(RolloutWorker pid=71720)
[36m(RolloutWorker pid=71720)[39m The above exception was the direct cause of the following exception:
[36m(RolloutWorker pid=71720)
[36m(RolloutWorker pid=71720)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
[36m(RolloutWorker pid=71720)[39m     self.run()
[36m(RolloutWorker pid=71720)[39m   File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 44, in run
[36m(RolloutWorker pid=71720)[39m     result = run_game(  # run_game is a function that runs the game.
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 496, in run_game
[36m(RolloutWorker pid=71720)[39m     result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
[36m(RolloutWorker pid=71720)[39m     return loop.run_until_complete(main)
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
[36m(RolloutWorker pid=71720)[39m     return future.result()
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 369, in _host_game
[36m(RolloutWorker pid=71720)[39m     result = await _play_game(players[0], client, realtime, portconfig, game_time_limit, rgb_render_config)
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 218, in _play_game
[36m(RolloutWorker pid=71720)[39m     player_id = await client.join_game(
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\client.py", line 99, in join_game
[36m(RolloutWorker pid=71720)[39m     result = await self._execute(join_game=req)
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\protocol.py", line 68, in _execute
[36m(RolloutWorker pid=71720)[39m     response = await self.__request(sc_pb.Request(**kwargs))
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\protocol.py", line 51, in __request
[36m(RolloutWorker pid=71720)[39m     raise ConnectionAlreadyClosed("Connection already closed.") from exc
[36m(RolloutWorker pid=71720)[39m sc2.protocol.ConnectionAlreadyClosed: Connection already closed.
[36m(RolloutWorker pid=71720)[39m Exception in thread Thread-4:
[36m(RolloutWorker pid=71720)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\yarl\_url.py", line 191, in __new__
[36m(RolloutWorker pid=71720)[39m     port = val.port
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\urllib\parse.py", line 177, in port
[36m(RolloutWorker pid=71720)[39m     raise ValueError(f"Port could not be cast to integer value as {port!r}")
[36m(RolloutWorker pid=71720)[39m ValueError: Port could not be cast to integer value as 'None'
[36m(RolloutWorker pid=71720)
[36m(RolloutWorker pid=71720)[39m The above exception was the direct cause of the following exception:
[36m(RolloutWorker pid=71720)
[36m(RolloutWorker pid=71720)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 423, in _request
[36m(RolloutWorker pid=71720)[39m     url = self._build_url(str_or_url)
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 357, in _build_url
[36m(RolloutWorker pid=71720)[39m     url = URL(str_or_url)
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\yarl\_url.py", line 193, in __new__
[36m(RolloutWorker pid=71720)[39m     raise ValueError(
[36m(RolloutWorker pid=71720)[39m ValueError: Invalid URL: port can't be converted to integer
[36m(RolloutWorker pid=71720)
[36m(RolloutWorker pid=71720)[39m The above exception was the direct cause of the following exception:
[36m(RolloutWorker pid=71720)
[36m(RolloutWorker pid=71720)[39m Traceback (most recent call last):
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
[36m(RolloutWorker pid=71720)[39m     self.run()
[36m(RolloutWorker pid=71720)[39m   File "c:\Users\Emil WC\Bachelor\RL-SC2-bot\QueueEnv.py", line 44, in run
[36m(RolloutWorker pid=71720)[39m     result = run_game(  # run_game is a function that runs the game.
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 496, in run_game
[36m(RolloutWorker pid=71720)[39m     result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
[36m(RolloutWorker pid=71720)[39m     return loop.run_until_complete(main)
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
[36m(RolloutWorker pid=71720)[39m     return future.result()
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\main.py", line 357, in _host_game
[36m(RolloutWorker pid=71720)[39m     async with SC2Process(
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\sc2process.py", line 108, in __aenter__
[36m(RolloutWorker pid=71720)[39m     self._ws = await self._connect()
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\sc2\sc2process.py", line 215, in _connect
[36m(RolloutWorker pid=71720)[39m     ws = await self._session.ws_connect(self.ws_url, timeout=120)
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 779, in _ws_connect
[36m(RolloutWorker pid=71720)[39m     resp = await self.request(
[36m(RolloutWorker pid=71720)[39m   File "C:\Users\Emil WC\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 425, in _request
[36m(RolloutWorker pid=71720)[39m     raise InvalidURL(str_or_url) from e
[36m(RolloutWorker pid=71720)[39m aiohttp.client_exceptions.InvalidURL: ws://127.0.0.1:None/sc2api
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:06.220 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at None...
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:06.220 | INFO     | sc2.sc2process:_clean:242 - Cleaning up...
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:06.220 | INFO     | sc2.sc2process:_clean:274 - Cleanup complete
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:06.286 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at None...
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:06.286 | INFO     | sc2.sc2process:_clean:242 - Cleaning up...
[36m(RolloutWorker pid=71720)[39m 2023-06-08 10:16:06.287 | INFO     | sc2.sc2process:_clean:274 - Cleanup complete
[33m(raylet)[39m [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:581] String field 'ray.rpc.WorkerTableData.exit_detail' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
[33m(raylet)[39m [2023-06-08 10:16:10,995 E 74152 77748] (raylet.exe) logging.cc:97: Unhandled exception: class nlohmann::detail::type_error. what(): [json.exception.type_error.316] invalid UTF-8 byte at index 584: 0x72
[33m(raylet)[39m [2023-06-08 10:16:11,005 E 74152 77748] (raylet.exe) logging.cc:104: Stack trace:
[33m(raylet)[39m  unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m terminate
[33m(raylet)[39m _NLG_Return2
[33m(raylet)[39m _NLG_Return2
[33m(raylet)[39m _CxxFrameHandler4
[33m(raylet)[39m unknown
[33m(raylet)[39m _chkstk
[33m(raylet)[39m RtlFindCharInUnicodeString
[33m(raylet)[39m RtlRaiseException
[33m(raylet)[39m RaiseException
[33m(raylet)[39m CxxThrowException
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m unknown
[33m(raylet)[39m BaseThreadInitThunk
[33m(raylet)[39m RtlUserThreadStart
[33m(raylet)
[33m(raylet)[39m *** SIGABRT received at time=1686212171 ***
[33m(raylet)[39m     @   00007FFE10F6F601  (unknown)  abort
[33m(raylet)[39m     @   00007FF704E57F36  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FFE10F6ED32  (unknown)  terminate
[33m(raylet)[39m     @   00007FFDDA051AAB  (unknown)  _NLG_Return2
[33m(raylet)[39m     @   00007FFDDA052317  (unknown)  _NLG_Return2
[33m(raylet)[39m     @   00007FFDDA0540D9  (unknown)  _CxxFrameHandler4
[33m(raylet)[39m     @   00007FF7052EAAFC  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FFE136D3CFF  (unknown)  _chkstk
[33m(raylet)[39m     @   00007FFE1364E456  (unknown)  RtlFindCharInUnicodeString
[33m(raylet)[39m     @   00007FFE13684455  (unknown)  RtlRaiseException
[33m(raylet)[39m     @   00007FFE10AB536C  (unknown)  RaiseException
[33m(raylet)[39m     @   00007FFDDA876480  (unknown)  CxxThrowException
[33m(raylet)[39m     @   00007FF704DFA325  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704DF9A53  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704DF975E  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E6BC61  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E6946D  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E69AF2  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E6AA32  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E683E7  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704C26745  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704C47C41  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704C47694  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704BD2679  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E20056  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E20547  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E2DC0B  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E1D535  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E1914E  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF704E2272E  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF7052A311C  (unknown)  (unknown)
[33m(raylet)[39m     @   00007FF7052A6904  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361: *** SIGABRT received at time=1686212171 ***
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFE10F6F601  (unknown)  abort
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E57F36  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFE10F6ED32  (unknown)  terminate
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFDDA051AAB  (unknown)  _NLG_Return2
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFDDA052317  (unknown)  _NLG_Return2
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFDDA0540D9  (unknown)  _CxxFrameHandler4
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF7052EAAFC  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFE136D3CFF  (unknown)  _chkstk
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFE1364E456  (unknown)  RtlFindCharInUnicodeString
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFE13684455  (unknown)  RtlRaiseException
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFE10AB536C  (unknown)  RaiseException
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FFDDA876480  (unknown)  CxxThrowException
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704DFA325  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704DF9A53  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704DF975E  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E6BC61  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E6946D  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E69AF2  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E6AA32  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E683E7  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704C26745  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704C47C41  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704C47694  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704BD2679  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E20056  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E20547  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E2DC0B  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E1D535  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E1914E  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF704E2272E  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF7052A311C  (unknown)  (unknown)
[33m(raylet)[39m [2023-06-08 10:16:11,006 E 74152 77748] (raylet.exe) logging.cc:361:     @   00007FF7052A6904  (unknown)  (unknown)
[36m(pid=gcs_server)[39m [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:581] String field 'ray.rpc.WorkerTableData.exit_detail' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.